// Sistema-de-Banco-de-Dados-main/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css'],
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  async ngOnInit(): Promise<void> {
    this.editoras = this.servEditora.getEditoras();
    this.livros = await this.servLivros.obterLivros();
  }

  excluir = async (codigo: string): Promise<void> => {
    await this.servLivros.excluir(codigo);
    this.livros = await this.servLivros.obterLivros();
  };

  obterNome = (codEditora: number): string | undefined => {
    return this.servEditora.getNomeEditoras(codEditora);
  };
}

<main class="container mt-5">
  <h1 class="mb-4 text-center">Lista de Livros</h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Título</th>
        <th>Resumo</th>
        <th>Editora</th>
        <th>Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>
          {{ livro.titulo }}
          <button
            class="btn btn-danger btn-sm btn-block"
            (click)="excluir(livro._id)"
          >
            Excluir
          </button>
        </td>
        <td>{{ livro.resumo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</main>

// Sistema-de-Banco-de-Dados-main/livros-next/pages/LivroLista.tsx
import { useState, useEffect } from "react";
import { ControleLivros } from "../classes/controle/ControleLivros";
import { Livro } from "../classes/modelo/Livro";
import { Menu } from "../componentes/Menu";

const controleLivros = new ControleLivros();

const LinhaLivro = (props: { livro: Livro; excluir: (id: string) => void }) => {
  const { livro, excluir } = props;

  const livroId = livro._id ?? "";
  return (
    <tr>
      <td>
        <button onClick={() => excluir(livroId)} className="btn btn-danger">
          Excluir
        </button>
      </td>
      <td>{livro.titulo}</td>
      <td>{livro.resumo}</td>
      <td>{livro.codEditora}</td>
      <td>
        <ul>
          {livro.autores.map((autor, index) => (
            <li key={index}>{autor}</li>
          ))}
        </ul>
      </td>
    </tr>
  );
};

const LivroLista = () => {
  const [livros, setLivros] = useState<Livro[]>([]);

  useEffect(() => {
    controleLivros.obterLivros().then((livros) => {
      setLivros(livros);
    });
  }, []);

  const excluir = (id: string) => {
    if (!id) {
      alert("ID do livro não encontrado.");
      return;
    }

    controleLivros.excluirLivro(id).then((sucesso) => {
      if (sucesso) {
        setLivros((livrosAntigos) =>
          livrosAntigos.filter((livro) => livro._id !== id)
        );
      } else {
        alert("Erro ao excluir livro.");
      }
    });
  };

  return (
    <main>
      <Menu /> {}
      <h1>Lista de Livros</h1>
      <table className="table">
        <thead>
          <tr>
            <th>Ações</th>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th>Autores</th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro, index) => (
            <LinhaLivro key={index} livro={livro} excluir={excluir} />
          ))}
        </tbody>
      </table>
    </main>
  );
};

export default LivroLista;
